version: '3.8'

services:
  main:
    image: main
    build:
      context: .
    ports:
      - "8080:8080"
    networks:  # Подключаем к сети
      - app-network
    develop:
      watch:
        - action: rebuild
          path: .
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: vk
    networks:  # Подключаем к той же сети
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -Upostgres -d vk"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s

# Определяем общую сеть
networks:
  app-network:
    driver: bridge